### ISSUE TITLE
Lisans hakkında bilgi ricası

### ISSUE THREAD

**Issue by hwpplayer1** [mguludag/Cpp_Ders_Notlar-_-CSDernegi-#2]
Merhaba, 

Öyle zannediyorum ki siz benim de yapmaya çalıştığım gibi sıfırdan kod yazıp kendi lisansınızı belirleyeceksiniz.

Bahsedilen GPLv3+ lisansı nerelerde geçerli, yukarıda belirttiğim kendi içeriklerinizde değil mi ?

Eğer öyleyse daha resmi ve standartlara uygun olması açısından her kaynak kodu dosyasının başına kendi isminizi eklemenizi önerebilirim. Böylelikle lisans kontrolü yapılırken daha doğru sonuç alınıyor. 

Teşekkürler

**Comment by mguludag** [comment]
Merhaba,

Bu içerikte var olan bilgi üzerinde ekleme çıkarma yapmadım ders notu içinde daha efektif gezinmek için kelime işlemciye çeşitli ayarlamalar yaptım index oluşturdum. Lisans konusu ise ne seçtiğimin farkında değildim ve içeriği üretenlerin ismini belirtip faklı reklamları temizlemiştim.

Diğer repo larda kaynak kodların üzerine lisans eklememiştim ama template bulmuştum ve yeni projelerde otomatik ekleniyor artık.

Teşekkürler

**Comment by hwpplayer1** [comment]
Anladığım kadarıyla, önerebileceğim şey ders notlarını ayrı bir branch'te tutmak ve devel branch'i gibi bir branch'te de sizin kendinize ait içeriklerinizi kendi lisansınızla barındırmanız olacak.

Teşekkürler, iyi bayramlar

**Comment by mguludag** [comment]
Bu repoda kendime ait içerik yok bu yüzden sadece lisansı değiştirmem yeterli sanırım.

Teşekkürler, iyi bayramlar...

**Comment by hwpplayer1** [comment]
> Bu repoda kendime ait içerik yok bu yüzden sadece lisansı değiştirmem yeterli sanırım.
> 
> Teşekkürler, iyi bayramlar...

Aslında bir lisans var gibi, eserin sahibi örneğin Kaan ASLAN hocamız "kaynak gösterilmek şartıyla" demiş. Bu MIT/Expat lisansı olarak kabul edilir mi bilmiyorum. CSD Derneği arayıp sormak lazım.

Amacım bir lisans dayatması veya farklı bir dayatma değil. Ben de Git kullanmayı yeni yeni öğreniyorum. Dilerseniz ortak içerik üretebiliriz. 

Teşekkürler, iyi çalışmalar

**Comment by mguludag** [comment]
MIT lisansı ekledim içerik sahipleri adına. Ortak içerik için varolan bir repoya da katkıda bulunulabilir.

Teşekkürler, sizede iyi çalışmalar

**Comment by hwpplayer1** [comment]
> MIT lisansı ekledim içerik sahipleri adına. Ortak içerik için varolan bir repoya da katkıda bulunulabilir.
> 
> Teşekkürler, sizede iyi çalışmalar

Önerebileceğiniz bir depo varsa başlamak isterim. Teşekkürler
